codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "0..100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: false

    patch:
      default:
        target: 80%
        threshold: 5%
        informational: false