name: Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  checkout:
    name: Checkout & Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Build
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref != 'refs/heads/none' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: .
          if-no-files-found: error

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo builds
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --workspace --locked --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-llvm-cov
        run: |
          if ! command -v cargo-llvm-cov &> /dev/null; then
            cargo install cargo-llvm-cov
          else
            echo "cargo-llvm-cov is already installed"
          fi

      - name: Run cargo llvm-cov (workspace)
        run: cargo llvm-cov --workspace --all-features --lcov --output-path coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          fail_ci_if_error: true
          verbose: true