name: Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  tests_and_coverage:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust (stable & llvm-tools)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: System-Dependencies (X11/ALSA etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config libx11-dev libasound2-dev libudev-dev \
            libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev zip

      - name: Install cargo-llvm-cov
        run: |
          if ! command -v cargo-llvm-cov &> /dev/null; then
            cargo install cargo-llvm-cov
          else
            echo "cargo-llvm-cov is already installed"
          fi

      - name: Run tests with coverage (workspace)
        run: cargo llvm-cov --workspace --all-features --lcov --output-path coverage.lcov

      - name: Upload lcov to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          fail_ci_if_error: true
          verbose: true